*	Use the timeseries data to analyse;
proc summary missing data=timeseries;
	class country date;
	var cases;
	output out=timeseries_country_tmp (where=(_type_ in (1 3))) sum=;
run;
data timeseries_country;
	set timeseries_country_tmp;
	country=ifc(missing(country),'Global',country);
run;
*	Plot of some key countries;
title "COVID-19 Cases by Country";
proc sgplot data=timeseries_country (where=(country in ('Global','US','Italy','Spain','Australia')));
	where cases >= 1;
	series x=date y=cases / group=country;
	xaxis label='Date' grid ;
	yaxis label='Cases' grid type=log logstyle=logexpand logbase=10;
	keylegend;
run;
