*	Get the current working directory (note this is for windows);
filename pwd pipe "echo %cd%";
data _null_;
	infile pwd;
	input;
	put _infile_;
	pwd=tranwrd(_infile_,'0d'x,'');
	call symputx('pwd',pwd);
run;
%put pwd: &pwd.;
libname covid "&pwd.";